@URL_API=http://localhost:5000

### HOME
GET {{URL_API}}

### All BOOKS
GET {{URL_API}}/books

###  All USERS
GET {{URL_API}}/users

### Check if I am still logged in and give me my user info
GET {{URL_API}}/users/me

### Create USER / signup
POST {{URL_API}}/users
Content-Type: application/json

{
    "name": "sara",
    "email": "sara@gmail.com",
    "password": "sara1"
}  

### Login USER 
POST {{URL_API}}/users/login
Content-Type: application/json

{
    "email": "sara@gmail.com",
    "password": "sara1"
} 
  
### Logout USER
GET {{URL_API}}/users/logout