@url=http://localhost:5000

### HOME
GET {{url}}

### All BOOKS
GET {{url}}/books

###  All USERS
GET {{url}}/users

### Check if I am still logged in and give me my user info
GET {{url}}/users/me


### Create USER / signup
POST {{url}}/users
Content-Type: application/json

{
    "name": "aman",
    "email": "aman@gmail.com",
    "password": "aman1"
}  

### Login USER 
POST {{url}}/users/login
Content-Type: application/json

{
    "email": "aman@gmail.com",
    "password": "aman1"
} 
  
### Logout USER
GET {{url}}/users/logout