@url=http://localhost:5000

### home
GET {{url}}

### books
GET {{url}}/books

###  All users
GET {{url}}/users

###  user Create / signup
POST {{url}}/users
Content-Type: application/json

{
    "name": "rosa",
    "email": "rosa@gmail.com",
    "password": "rosa1"
}  
###  Login user
POST {{url}}/users/login
Content-Type: application/json

{
    "email": "rosa@gmail.com",
    "password": "rosa1"
} 