@url=http://localhost:5000

### home
GET {{url}}

### books
GET {{url}}/books

### users All
GET {{url}}/users

### user Create
POST {{url}}/users
Content-Type: application/json

{
    "name": "John",
    "email": "john@John.com",
    "password": "john1"
} 